apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cv-screener

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - persistent-volumes.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: cv-screener
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
